### ISSUE TITLE
Hyperparameter Advice

### ISSUE THREAD

**Issue by Random-Word** [haarnoja/sac#12]
Hi Tuomas. I'm trying out your SAC implementation on some of the continuous gym environments and I'm curious if you have any recommendations for how to best tune the hyperparameters. Using the defaults and a temperature of 1, for instance, leads to some wildly oscillating policy performance on LunarLanderContinuous or InvertedPendulum. The policy may generate very good returns, then suddenly in the next entry in progress.csv terrible returns, and oscillates up and down without stabilizing. Does that suggest the temperature parameter needs to be tuned, or are some of the other default hyperparameters not ideal for these sorts of tasks?

An example of the episode return for lunar lander against samples:
![lunarlandersac](https://user-images.githubusercontent.com/2447893/43669543-9defeaf0-9738-11e8-9541-8a9c8213e314.png)

Thanks!

**Comment by haarnoja** [comment]
Learning tasks that require high precision can be hard with maximum entropy rl algorithms. There can be lots of variation in returns since the optimal policy is stochastic. You can try evaluating the policy using the mean action when using a Gaussian representation, which could give more consistent results. Using the mean instead of sampling from the policy distribution is just a heuristic and is not guaranteed to work, but at least on simulated locomotion tasks it seems to help.

You can also take a look at the entropy to tune the reward scale. A good rule of thumb is to have average entropy roughly equal to the negative of the number of action dimensions.

**Comment by Random-Word** [comment]
It was using a deterministic evaluation policy, but the GMM policy without the reparamaterization trick was unstable over a wide range of temperatures for this task. Your update nine days ago to match the latest paper made the results much more reliable. Thanks!

![image](https://user-images.githubusercontent.com/2447893/44128161-38f8b5c0-9ff6-11e8-8b3c-865391d8781f.png)
