### ISSUE TITLE
is chainer dep necessary?

### ISSUE THREAD

**Issue by vlad17** [haarnoja/sac#2]
With my cudnn7 install the chainer dependency breaks the local install steps. Removing it from the environment.yml doesn't seem to break anything

**Comment by hartikainen** [comment]
Yup, you're right. There might be other dependencies as well in the environment.yaml that are not necessarily needed by the sac algorithm. The environment.yml was started as a copy of [rllab](https://github.com/rll/rllab)s environment.yml file due to complications with the rllab installation, and is left unpruned until a better way of installing rllab dependency is found.

**Comment by haarnoja** [comment]
I have finally removed this dependency along with some other deps.
